### ISSUE TITLE
setup vue example error

### ISSUE THREAD

**Issue by wulie88** [alibaba/schema-plugin-flow#1]
following shells:

```
$ git clone https://github.com/alibaba/schema-plugin-flow.git
$ cd schema-plugin-flow
$ npm run i
$ npm run i-vue
$ npm run start-vue
```

show error on `npm run start-vue`

 ERROR  Failed to compile with 1 errors    

This relative module was not found:

* ./lib/index.js in ../packages/sifo-vue/index.js

**Comment by qq5050595531** [comment]
The same with me.

**Comment by qq5050595531** [comment]
> following shells:
> 
> ```
> $ git clone https://github.com/alibaba/schema-plugin-flow.git
> $ cd schema-plugin-flow
> $ npm run i
> $ npm run i-vue
> $ npm run start-vue
> ```
> 
> show error on `npm run start-vue`
> 
> ERROR Failed to compile with 1 errors
> 
> This relative module was not found:
> 
> * ./lib/index.js in ../packages/sifo-vue/index.js

if you just want to see  how it run. you can run :
```
cd ./examples-vue
npm uninstall @schema-plugin-flow/sifo-vue -s 
npm install @schema-plugin-flow/sifo-vue -s
```

**Comment by FrominXu** [comment]
> following shells:
> 
> ```
> $ git clone https://github.com/alibaba/schema-plugin-flow.git
> $ cd schema-plugin-flow
> $ npm run i
> $ npm run i-vue
> $ npm run start-vue
> ```
> 
> show error on `npm run start-vue`
> 
> ERROR Failed to compile with 1 errors
> 
> This relative module was not found:
> 
> * ./lib/index.js in ../packages/sifo-vue/index.js

I've tried to run these shells and they work well.

It build libs after run 'npm run i'，did you see any error after 'npm run i' ?

or you can try like what @qq5050595531 said.
