### ISSUE TITLE
sifo-mplg-form-fusion 不支持 defaultValue 

### ISSUE THREAD

**Issue by Hu-xiaojian** [alibaba/schema-plugin-flow#10]
不支持mApi.getValues()获取schema模版上defaultValue；
select选择器属性itemVisible 不生效；

**Comment by FrominXu** [comment]
defaultValue 能力已经支持；
itemVisible 字段显隐已经支持；
@schema-plugin-flow/sifo-mplg-form-fusion v1.2.0
