### ISSUE TITLE
可以在uniapp中使用吗

### ISSUE THREAD

**Issue by Adgeros** [alibaba/schema-plugin-flow#2]
我的需求是在uniapp项目中使用，目前项目是uniapp开发的，已经完成

**Comment by FrominXu** [comment]
官方提供的sifo-vue是使用 Vue 的 _render_ 能力来实现UI渲染的，在 uniapp 中应该是不能完全适用的。sifo-model本身是UI无关的，可以尝试在这一层上建立你需要的功能。

**Comment by FrominXu** [comment]
> 我的需求是在uniapp项目中使用，目前项目是uniapp开发的，已经完成

官方提供的sifo-vue是使用 Vue 的 render 能力来实现UI渲染的，在 uniapp 中应该是不能完全适用的。sifo-model本身是UI无关的，可以尝试在这一层上建立你需要的功能。

**Comment by Adgeros** [comment]
> > 我的需求是在uniapp项目中使用，目前项目是uniapp开发的，已经完成
> 
> 官方提供的sifo-vue是使用 Vue 的 render 能力来实现UI渲染的，在 uniapp 中应该是不能完全适用的。sifo-model本身是UI无关的，可以尝试在这一层上建立你需要的功能。

是扩展 sifo-model 吗

**Comment by FrominXu** [comment]
> > > 我的需求是在uniapp项目中使用，目前项目是uniapp开发的，已经完成
> > 
> > 
> > 官方提供的sifo-vue是使用 Vue 的 render 能力来实现UI渲染的，在 uniapp 中应该是不能完全适用的。sifo-model本身是UI无关的，可以尝试在这一层上建立你需要的功能。
> 
> 是扩展 sifo-model 吗

是的，封装sifo-model再配合模型插件等来实现你想要的功能。不过uniapp依赖特殊的打包，可能无法实现所有的sifo能力。

**Comment by Adgeros** [comment]
> > > > 我的需求是在uniapp项目中使用，目前项目是uniapp开发的，已经完成
> > > 
> > > 
> > > 官方提供的sifo-vue是使用 Vue 的 render 能力来实现UI渲染的，在 uniapp 中应该是不能完全适用的。sifo-model本身是UI无关的，可以尝试在这一层上建立你需要的功能。
> > 
> > 
> > 是扩展 sifo-model 吗
> 
> 是的，封装sifo-model再配合模型插件等来实现你想要的功能。不过uniapp依赖特殊的打包，可能无法实现所有的sifo能力。

目前我测试了一下可以正常跑起来 hello world 页面，后续功能我在测试看看
