### ISSUE TITLE
表单数据维护问题

### ISSUE THREAD

**Issue by xuzhouchen1104** [alibaba/schema-plugin-flow#3]
你好，一些公共数据可以使用 mApi.setGlobalData 方法存储。而像表单数据应在schema上维护。
比如一个表单 涉及姓名，年龄，
数据格式为 const a ={
                         age：'',
                         name: ''
                    }
那怎么维护对象a 呢，比如我需要a为全局对象，age改变后，需要更新a的数据，并保存到vuex中，
plugin 中 setAttributes 的话，需要把{
                                                             age：'',
                                                             name: ''
                                                            }  都传进去，有没有更好的办法呢

**Comment by FrominXu** [comment]
对于一个sifo-app组件，其本身可用来管理数据，与vuex是相似的角色。
而如果sifo-app组件在一个vuex项目内部，需要将sifo-app与vuex通信时，可借助sifo.watch（或给模型插件追加功能）与vuex插件的能力同步。

对于维护数据到一个统一地方的情形，比如你期望最终的数据都回到vuex里，而表单字段的变更是在sifo的组件插件的change方法上捕获。
一方面，你需要用setAttributes方法将value写到相应的schema节点上维护sifo内部状态；
`
        mApi.addEventListener(id, 'change', (c, e) => {
          c.mApi.setAttributes(id, { value: e.target.value })
        });
`

另一方面，你可以单独为表单字段注册watch，用来将数据同步到vuex。一种方式可以单独加一个组件插件专门做这个事情，另一种方式是将此能力放到专门的模型插件里。
`
        mApi.watch(id, (ctx) => { 
          // to vuex
        })
`
这类工作可以统一来做，比如用一个标识标注哪类节点是字段节点，使用queryNodeIds方法统一进行：
`
    {
      "component": "a-date-picker",
      "id": "date",
      "isField": true,
      "attributes": {
        "type": "primary",
        "placeholder": "日期"
      }
    }

mApi.queryNodeIds(node => node.isField).forEach(id => {
        mApi.addEventListener(id, 'change', (c, e) => {
          c.mApi.setAttributes(id, { value: e.target.value })
        });
        mApi.watch(id, (ctx) => { 
          // to vuex
        });
      });
`

**Comment by xuzhouchen1104** [comment]
感谢大佬回答，就是还有个疑问，我想维护的是整个表单对象 比如 我只是想把整个form 更新到vuex 
form:{
  age：'',
  name: ''
}
我是在哪里维护这个form对象呢，我看你上面的例子都是维护的单个字段数据，而不是整个form对象。
有什么好的方法吗（基本方法就是每次都获取各个表单字段数据，将他们塞到form 里面）

**Comment by FrominXu** [comment]
> 感谢大佬回答，就是还有个疑问，我想维护的是整个表单对象 比如 我只是想把整个form 更新到vuex
> form:{
> age：'',
> name: ''
> }
> 我是在哪里维护这个form对象呢，我看你上面的例子都是维护的单个字段数据，而不是整个form对象。
> 有什么好的方法吗（基本方法就是每次都获取各个表单字段数据，将他们塞到form 里面）

我有点疑惑的是，为何会有一个单独的formData既不是在vuex内，也不是直接通过schema维护的呢？

目前我正在开发的一个通用表单模型插件，所有的字段数据都是维护在schema字段节点上，其它地方需要使用可以直接获取（我在模型插件里写了 getValue[s]/setValue[s] 方法扩展到mApi上），这种方式比较符合sifo的设计。

我看到你在邮箱内的代码示例，是将一个数据直接放到js模块上了，这种方式个人觉得不太合理，因为js模块上的变量是公用的，而且只有一份，表单的数据应该在表单实例内部维护，否则在一些场景（比如一个页面有多个该表单实例，或实例有销毁重渲染过程）会导致数据污染。

如果你依然想将formData放到一个统一的位置，那可以提供get/set方法暴露给外部使用，mApi中去调用该方法，维护过程同我上一条的回复。

**Comment by xuzhouchen1104** [comment]
了解，感谢

**Comment by FrominXu** [comment]
> 了解，感谢

sifo-mplg-form-core and sifo-mplg-form-antdv had been published. you can trying vue-demos in Vue case.

**Comment by songyule** [comment]
> 对于一个sifo-app组件，其本身可用来管理数据，与vuex是相似的角色。
> 而如果sifo-app组件在一个vuex项目内部，需要将sifo-app与vuex通信时，可借助sifo.watch（或给模型插件追加功能）与vuex插件的能力同步。
> 
> 对于维护数据到一个统一地方的情形，比如你期望最终的数据都回到vuex里，而表单字段的变更是在sifo的组件插件的change方法上捕获。
> 一方面，你需要用setAttributes方法将value写到相应的schema节点上维护sifo内部状态；
> `mApi.addEventListener(id, 'change', (c, e) => { c.mApi.setAttributes(id, { value: e.target.value }) });`
> 
> 另一方面，你可以单独为表单字段注册watch，用来将数据同步到vuex。一种方式可以单独加一个组件插件专门做这个事情，另一种方式是将此能力放到专门的模型插件里。
> `mApi.watch(id, (ctx) => { // to vuex })`
> 这类工作可以统一来做，比如用一个标识标注哪类节点是字段节点，使用queryNodeIds方法统一进行：
> `
> {
> "component": "a-date-picker",
> "id": "date",
> "isField": true,
> "attributes": {
> "type": "primary",
> "placeholder": "日期"
> }
> }
> 
> mApi.queryNodeIds(node => node.isField).forEach(id => {
> mApi.addEventListener(id, 'change', (c, e) => {
> c.mApi.setAttributes(id, { value: e.target.value })
> });
> mApi.watch(id, (ctx) => {
> // to vuex  _这里面是怎么拿到vuex相关的属性的通过externals吗_
> });
> });
> `
大佬，to vuex 有点疑问，在watch的回调里是怎么拿到vuex相关属性的

**Comment by FrominXu** [comment]
> > 对于一个sifo-app组件，其本身可用来管理数据，与vuex是相似的角色。

> > 大佬，to vuex 有点疑问，在watch的回调里是怎么拿到vuex相关属性的

在sifo-vue下有扩展mApi方法： mApi.getSifoVueInstance() 得到vue组件实例，通过这个实例可以拿到$store
