### ISSUE TITLE
单纯使用SifoFormCoreModelPlugin ，原生input ，rules 和label 没用吗

### ISSUE THREAD

**Issue by xuzhouchen1104** [alibaba/schema-plugin-flow#4]
如题，

**Comment by FrominXu** [comment]
> 如题，

可以用的，SifoFormCore 是不依赖组件库的。
事件：原生input只需要给这个模型插件绑定合适的fieldChange即可。
样式与布局：label 与 rules 校验信息展示，需要像sifo-mplg-form-antd、sifo-mplg-form-antdv 一样实现想要的UI层模型插件，做的事情很简单，可以参考这两个UI层模型插件的原码自己实现一个模型插件。
同时，你也可以在此基础上注册组件插件，为指定字段单独处理值变更事件。
