### ISSUE TITLE
使用iview 组件库 table 组件，其中resizable 失效，无法拖拽调整该列的宽度

### ISSUE THREAD

**Issue by xuzhouchen1104** [alibaba/schema-plugin-flow#5]
![image](https://user-images.githubusercontent.com/48044617/98524934-c5069c80-22b2-11eb-81cc-8246892862b3.png)

代码使用如下：  无法拖拽调整该列的宽度
 
![image](https://user-images.githubusercontent.com/48044617/98525129-08610b00-22b3-11eb-8f25-f915027d1828.png)

**Comment by xuzhouchen1104** [comment]
独自抽成一个组件，然后columns 放在组件里面可以，类似这样
![image](https://user-images.githubusercontent.com/48044617/98527430-f9c82300-22b5-11eb-9719-1ebfec063114.png)，但是提取出来放attributes 就会失效

**Comment by FrominXu** [comment]
> ![image](https://user-images.githubusercontent.com/48044617/98524934-c5069c80-22b2-11eb-81cc-8246892862b3.png)
> 
> 代码使用如下： 无法拖拽调整该列的宽度
> 
> ![image](https://user-images.githubusercontent.com/48044617/98525129-08610b00-22b3-11eb-8f25-f915027d1828.png)

因为i-table的列宽依赖width属性，在调整列宽时，会更新该属性。而在sifo上，columns属性是作为props传入的，props不允许直接更改。
如何解决：可以使用on-column-width-resize方法，在sifo插件中用addEventListener监听此方法，并在该方法触发时用setAttributes更新相应列的width属性。
类似下图的onColResize的用法
![image](https://user-images.githubusercontent.com/22270325/98534776-f0dc4f00-22bf-11eb-9204-e446e62f436c.png)

**Comment by xuzhouchen1104** [comment]
xiexie
